block-beta
    columns 4

    block:SSH_p:5
        ssh_auth_p["SSH User Authentication Protocol"]
        ssh_conn_p["SSH Connection Protocol"]
    end

    block:SSH_t:5
        ssh_transport_p["SSH Transport Layer Protocol"]
    end

    block:TCP:5
        tcp["TCP"]
    end

    block:IP:5
        ip["IP"]
    end
    style ip fill:#d4efdf, stroke-width:0px
    style tcp fill:#fcf3cf, stroke-width:0px
    style ssh_transport_p fill:#d4e6f1, stroke-width:0px
    style ssh_conn_p fill:#f5b7b1, stroke-width:0px
    style ssh_auth_p fill: #d7bde2, stroke-width:0px
    style SSH_p fill:#ddd, stroke:#000,stroke-width:1px
    style SSH_t fill:#ddd, stroke:#000,stroke-width:1px
    style TCP fill:#ddd, stroke:#000,stroke-width:1px
    style IP fill:#ddd, stroke:#000,stroke-width:1px

