sequenceDiagram
    participant c as SSH client
    participant s as SSH server
    participant n as NSS
    participant p as PAM
    c->>s: SSH_MSG_USERAUTH_REQUEST
    activate s
    s ->> n: Request NSS
    activate n
    Note over c,n: According to settings in the /etc/nsswitch.conf NSS look up user the each data source. On this step the custom NSS <br/>module  must create a new user and return NSS_STATUS_SUCCESS if username matches the requirement
    alt does not user exist?
        n ->> s: NSS_STATUS_NOTFOUND
        s ->> c: SSH_MSG_USERAUTH_FAILURE
        opt
            s ->> c: Authentication method list
        end
    else user exists
        n ->> s: NSS_STATUS_SUCCESS
        c->>s: SSH_MSG_USERAUTH_REQUEST <br> + <br> Authentication method has been selected
        deactivate n
        s->>p: Request PAM
        activate p
        Note over s,p: According to settings in files to the /etc/pam.d PAM performs each module. On this step the custom PAM module must check SSH_AUTH_INFO_0, <br/>get pubkey and additional info (e.g. Key ID field) as well as return status if username, pubkey type, etc. matche the requirement.
            alt is not successful
                p ->> s: PAM_SESSION_ERR, PAM_AUTH_ERR, etc.
                s ->> c: SSH_MSG_USERAUTH_FAILURE
            else successful
                p ->> s: PAM_SUCCESS
            end
        alt is additional authentication method required
            s ->> c: Partial success
            s ->> p: .
            Note over c, p: Step(s) related to additional authentication method(s)
            p ->> s: .
            s ->>c: SSH_MSG_USERAUTH_SUCCESS
        else additional authentication method(s) is not required
            s ->>c: SSH_MSG_USERAUTH_SUCCESS
        end
        deactivate p
    end
    deactivate s
    activate c
     Note over c, p: Session has been opened
    c ->>s: Session terminate
    s ->>p: Session will be closed
    p ->>p: Some action(s)
    p ->>s: Sucessfully
    s->>c: Session has been closed
