sequenceDiagram
    participant s as SSH server
    participant n as NSS
    participant p as PAM
    activate s
    activate n
    s ->> n: Request NSS
    alt is user not found
        critical
            Note over s, n: On this step NSS module gets PID <br/>from SYSTED_EXEC_PID and <br/>looks up process name in /proc/PID/comm
            option calling process is not ssh
                n ->> s: NSS_STATUS_TRYAGAIN
            option username does not contain postfix
                n ->> s: NSS_STATUS_TRYAGAIN
        end
        n ->> n: Create user
        n ->> s: NSS_STATUS_SUCCESS
    else user is found
        critical
            option calling process is ssh
            option username does contain postfix
                n ->> s: NSS_STATUS_SUCCESS
        end
    end
    deactivate n
    s->>p: Request PAM
    activate p
    alt successfully
        critical check
        option SSH_AUTH_INFO_0
            p ->> p: looks up pubkey
        option pubkey type
        option gets Key ID
            p->> p: Create sudoerr file
        end
        p->>s:PAM_SUCCESS
    else not successfully
        p->>s: PAM_SESSION_ERR, PAM_AUTH_ERR, etc.
    end
    deactivate p
    deactivate s

