%%{init: {
    "flowchart" : { 'curve' : 'stepBefore', 'defaultRenderer': 'elk' }
  }
}%%
flowchart LR
    subgraph sshd_p[sshd process]
        direction TB
        sshd("sshd") ======> |If user exist <br>and<br> UsePAM enabled|libpam(PAM)
        subgraph libnss[NSS]
            direction RL
            nss{{"libs"}}
        end
        subgraph libpam[PAM]
            direction RL
            pam{{"libs"}}
        end
    end
    %% subgraph pamcfg[PAM configs]
        %% direction TB
        cfg{{"/etc/pam.d/*"}} ==> libpam
    %% end

    subgraph modules[PAM modules]
        pam ==> account
        pam ==> authentication
        pam ==> password
        pam ==> session
    end
    libnss <==> |Request<br>Response|sshd
    libpam ==> |Response|sshd

    classDef pam fill:#0f9d58;
    classDef nss fill:#eeac4d;
    classDef sshd_p fill:#f6f7fb
    class libpam pam
    class libnss nss
    class sshd_p sshd_p
    class modules sshd_p

