%%{
  init: {
    "flowchart" : { 'curve' : 'stepBefore', 'defaultRenderer': 'elk' }
  }
}%%
flowchart LR
    subgraph sshd_p[sshd process]
        direction TB
        sshd("sshd") ==> |Look up user|libnss(NSS)
        subgraph libnss[NSS]
            direction RL
            nss{{"libs"}}
        end
    end
    %% subgraph nss_config[NSS config]
        %% direction TB
        cfg{{"/etc/nsswitch.conf"}} ==> libnss
    %% end
    subgraph sources[Data Sources]
        nss ==> passwd ==> pwd_src(files<br>systemd)
        nss ==> group ==> grp_src(files)
        nss ==> networks ==> net_src(files<br>dns)
        nss ==> etc ==> etc.
    end
    libnss ==> |Response|sshd

    classDef nss fill:#eeac4d;
    classDef sshd_p fill:#f6f7fb
    class libnss nss
    class sshd_p sshd_p
    class sources sshd_p

