---
apiVersion: v1
kind: Pod
metadata:
  name: quarto-preview
spec:
  containers:
    - name: quarto
      image: ghcr.io/quarto-dev/quarto:1.7.1
      command:
        - quarto
        - preview
      workingDir: /srv
      ports:
        - containerPort: 6411
          hostPort: 6411
      volumeMounts:
        - name: source
          mountPath: /srv:Z
  volumes:
    - name: source
      hostPath:
        path: ./
        type: Directory

