name: Add RFDs to Quarto repository

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
    if: startsWith(github.ref, 'refs/tags/')

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Prepare
      run: |
        mkdir -p RFDs
        echo "[RFD source code](${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}){target="_blank"}" > _link.qmd
        tar -cf- * | tar -xf- --exclude quarto-preview.yaml --exclude README.md --exclude _quarto.yaml --exclude RFDs -C RFDs

    - name: Deploy
      uses: s0/git-publish-subdir-action@v2.6.0
      env:
        REPO: git@github.com:efrikin/efrikin.github.io.git
        BRANCH: main
        FOLDER: RFDs
        TARGET_DIR: RFDs
        MESSAGE: "[{sha}]: {msg}"
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}

